package embedded

import (
	"fmt"
	"path/filepath"
	"strings"
)

type torrcConfig struct {
	DataDir         string
	ControlPortFile string
	CookieAuthFile  string
	NoticeLog       string
	Quiet           bool
}

func renderTorrc(cfg torrcConfig) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# generated by haomad embedded tor bootstrap — do not hand-edit\n")
	fmt.Fprintf(&b, "DataDirectory %s\n", cfg.DataDir)
	fmt.Fprintf(&b, "ControlPort auto\n")
	fmt.Fprintf(&b, "ControlPortWriteToFile %s\n", cfg.ControlPortFile)
	fmt.Fprintf(&b, "CookieAuthentication 1\n")
	fmt.Fprintf(&b, "CookieAuthFile %s\n", cfg.CookieAuthFile)
	fmt.Fprintf(&b, "SocksPort auto\n")

	fmt.Fprintf(&b, "AvoidDiskWrites 1\n")
	if cfg.NoticeLog != "" {
		fmt.Fprintf(&b, "Log notice file %s\n", cfg.NoticeLog)
	}

	fmt.Fprintf(&b, "SafeLogging 1\n")

	return b.String()
}

func defaultTorrcPath(dataDir string) string   { return filepath.Join(dataDir, "torrc") }
func defaultControlFile(dataDir string) string { return filepath.Join(dataDir, "control.port") }
func defaultCookieFile(dataDir string) string  { return filepath.Join(dataDir, "control.cookie") }
func defaultNoticeLog(dataDir string) string   { return filepath.Join(dataDir, "tor.log") }
